# conda env create -f environment.yaml -p ./.venv

name: .venv
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - libmagic
  - pip:
      - langchain==0.3.26
      - langchain-community==0.3.27
      - openai==1.93.1
      - streamlit==1.46.1
      - python-dotenv==1.1.1
      - unstructured==0.18.3
      - tiktoken==0.9.0
      - faiss-cpu==1.11.0
      - python-magic==0.4.27
      - jupyter==1.1.1